# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec447718f7535421c3fa233b8101b73bbd3eacbaeba6be5c9730b3732a84c076a47cec17663d73a7483de88c9d3f1a42a25e65626a85474cc0a0e04072872572

test:
  secret_key_base: 576a6c5d993fa5886b52d8982f8506e467ad91cc5d534a18f3096ea1786c3547bfe6669ffd9a6a53322967bcd281edb2936db634610633473b42ab14d4597c6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
